# CI de Nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Testes unitarios com o Mocha'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  unit-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalacao do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

       # instalacao das dependencias
      - name: Instalando dependências
        run: npm install
      
      # executar os testes entregue no trabalho final da disciplina de programacao JS
      - name: Executando Testes do trabalho final da disciplina de JS
        run: npx mocha ./trabalho-final/testes/trabalho-final.js
